#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 The superseedr Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Superseedr Monitoring Interface

Polls and parses the status JSON file generated by Superseedr to monitor
download progress, connection status, and protocol version.
"""

import json
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class TorrentMetrics:
    """Metrics for a single torrent."""
    info_hash: str
    torrent_name: str
    total_bytes: int = 0
    downloaded_bytes: int = 0
    uploaded_bytes: int = 0
    download_rate_bps: int = 0
    upload_rate_bps: int = 0
    progress: float = 0.0
    is_complete: bool = False
    num_peers: int = 0
    num_seeds: int = 0
    state: str = "unknown"


@dataclass
class SuperseedrStatus:
    """Complete Superseedr application status."""
    run_time: int = 0
    cpu_usage: float = 0.0
    ram_usage_percent: float = 0.0
    total_download_bps: int = 0
    total_upload_bps: int = 0
    torrents: Dict[str, TorrentMetrics] = field(default_factory=dict)


class SuperseedrMonitor:
    """Monitors Superseedr via its status file."""
    
    def __init__(
        self,
        status_dir: Path,
        status_filename: str = "app_state.json",
        poll_interval: float = 0.5
    ):
        """
        Initialize the monitor.
        
        Args:
            status_dir: Directory containing status files
            status_filename: Name of the status JSON file
            poll_interval: How often to poll the status file (seconds)
        """
        self.status_dir = Path(status_dir)
        self.status_file = self.status_dir / "status_files" / status_filename
        self.poll_interval = poll_interval
        self._last_modified = 0.0
    
    def read_status(self) -> Optional[SuperseedrStatus]:
        """
        Read and parse the current status from file.
        
        Returns:
            SuperseedrStatus or None if file doesn't exist
        """
        if not self.status_file.exists():
            return None
        
        try:
            with open(self.status_file, "r") as f:
                data = json.load(f)
            
            return self._parse_status(data)
        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse status file: {e}")
            return None
        except Exception as e:
            logger.error(f"Error reading status file: {e}")
            return None
    
    def _parse_status(self, data: dict) -> SuperseedrStatus:
        """Parse raw JSON data into SuperseedrStatus."""
        status = SuperseedrStatus(
            run_time=data.get("run_time", 0),
            cpu_usage=data.get("cpu_usage", 0.0),
            ram_usage_percent=data.get("ram_usage_percent", 0.0),
            total_download_bps=data.get("total_download_bps", 0),
            total_upload_bps=data.get("total_upload_bps", 0),
        )
        
        # Parse torrent metrics
        torrents_data = data.get("torrents", {})
        for info_hash, metrics in torrents_data.items():
            status.torrents[info_hash] = TorrentMetrics(
                info_hash=info_hash,
                torrent_name=metrics.get("torrent_name", "unknown"),
                total_bytes=metrics.get("total_bytes", 0),
                downloaded_bytes=metrics.get("downloaded_bytes", 0),
                uploaded_bytes=metrics.get("uploaded_bytes", 0),
                download_rate_bps=metrics.get("download_rate_bps", 0),
                upload_rate_bps=metrics.get("upload_rate_bps", 0),
                progress=metrics.get("progress", 0.0),
                is_complete=metrics.get("is_complete", False),
                num_peers=metrics.get("num_peers", 0),
                num_seeds=metrics.get("num_seeds", 0),
                state=metrics.get("state", "unknown"),
            )
        
        return status
    
    def wait_for_torrent(
        self,
        info_hash: str,
        timeout: float = 60.0,
        min_progress: float = 1.0
    ) -> bool:
        """
        Wait for a specific torrent to reach minimum progress.
        
        Args:
            info_hash: The torrent info hash to monitor
            timeout: Maximum time to wait (seconds)
            min_progress: Minimum progress to wait for (0.0 - 1.0)
            
        Returns:
            True if torrent reached min_progress, False if timed out
        """
        start_time = time.time()
        logger.info(f"Waiting for torrent {info_hash[:16]}... to reach {min_progress*100:.1f}%")
        
        while time.time() - start_time < timeout:
            status = self.read_status()
            
            if status and info_hash in status.torrents:
                torrent = status.torrents[info_hash]
                
                if torrent.progress >= min_progress:
                    logger.info(
                        f"Torrent {info_hash[:16]}... reached {torrent.progress*100:.1f}% "
                        f"in {time.time() - start_time:.1f}s"
                    )
                    return True
                
                logger.debug(
                    f"Progress: {torrent.progress*100:.1f}% "
                    f"(DL: {torrent.download_rate_bps} B/s, Peers: {torrent.num_peers})"
                )
            
            time.sleep(self.poll_interval)
        
        logger.warning(f"Timeout waiting for torrent {info_hash[:16]}...")
        return False
    
    def wait_for_completion(
        self,
        info_hash: str,
        timeout: float = 120.0
    ) -> bool:
        """
        Wait for a torrent to complete (100% progress).
        
        Args:
            info_hash: The torrent info hash to monitor
            timeout: Maximum time to wait (seconds)
            
        Returns:
            True if completed, False if timed out
        """
        return self.wait_for_torrent(info_hash, timeout, min_progress=1.0)
    
    def get_torrent(self, info_hash: str) -> Optional[TorrentMetrics]:
        """Get metrics for a specific torrent."""
        status = self.read_status()
        if status:
            return status.torrents.get(info_hash)
        return None
    
    def list_torrents(self) -> List[TorrentMetrics]:
        """List all active torrents."""
        status = self.read_status()
        if status:
            return list(status.torrents.values())
        return []
    
    def is_running(self) -> bool:
        """Check if Superseedr is running by checking if status file exists."""
        return self.status_file.exists()
    
    def wait_for_startup(self, timeout: float = 30.0) -> bool:
        """
        Wait for Superseedr to start and create its status file.
        
        Args:
            timeout: Maximum time to wait
            
        Returns:
            True if started, False if timed out
        """
        start_time = time.time()
        
        while time.time() - start_time < timeout:
            if self.is_running():
                return True
            time.sleep(self.poll_interval)
        
        return False


def main():
    """CLI for testing the monitor."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Monitor Superseedr status")
    parser.add_argument("status_dir", help="Path to status directory")
    parser.add_argument(
        "--watch",
        action="store_true",
        help="Continuously watch status"
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=1.0,
        help="Poll interval in seconds"
    )
    
    args = parser.parse_args()
    
    monitor = SuperseedrMonitor(args.status_dir, poll_interval=args.interval)
    
    if args.watch:
        print("Watching Superseedr status... (Ctrl+C to stop)")
        try:
            while True:
                status = monitor.read_status()
                if status:
                    print(f"\n[{time.strftime('%H:%M:%S')}]")
                    print(f"Runtime: {status.run_time}s | CPU: {status.cpu_usage:.1f}% | RAM: {status.ram_usage_percent:.1f}%")
                    print(f"Total DL: {status.total_download_bps} B/s | Total UL: {status.total_upload_bps} B/s")
                    print(f"Torrents: {len(status.torrents)}")
                    for info_hash, torrent in status.torrents.items():
                        print(f"  {info_hash[:16]}...: {torrent.progress*100:.1f}% - {torrent.state}")
                else:
                    print("No status file found")
                time.sleep(args.interval)
        except KeyboardInterrupt:
            print("\nStopped")
    else:
        status = monitor.read_status()
        if status:
            print(json.dumps({
                "run_time": status.run_time,
                "cpu_usage": status.cpu_usage,
                "ram_usage_percent": status.ram_usage_percent,
                "torrent_count": len(status.torrents),
            }, indent=2))
        else:
            print("No status file found")


if __name__ == "__main__":
    main()
